# Generated by Django 5.2 on 2025-04-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='image',
        ),
    ]
