# Generated by Django 5.2 on 2025-04-26 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_enrollment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
    ]
